Repository ink-inc/MagicMittelalterGame, pull requests merged in 2020-04, with the labels that each got.

#109 FIX: git rm
  README.md
Labels: documentation, fix

#110 ADD: Weight Penalty
  Assets/Scenes/InventoryTest.unity
  Assets/Scripts/Inventory/Inventory.cs
  Assets/Scripts/Player/PlayerProperties.cs
Labels: enhancement

#117 UPDATE: Player Hitbox and Normalization of speed
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Player/PlayerController.cs
  Assets/UniGLTF.meta
Labels: improvement, minor feature

#111 Sound system/music manager
  .gitattributes
  Assets/Music.meta
  Assets/Music/510953__theojt__cinematic-battle-song.mp3
  Assets/Music/510953__theojt__cinematic-battle-song.mp3.meta
  Assets/Music/A1-Cave.mp3
  Assets/Music/A1-Cave.mp3.meta
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Areas.meta
  Assets/Scripts/Areas/BattleCube.cs
  Assets/Scripts/Areas/BattleCube.cs.meta
  Assets/Scripts/Areas/StartArea.cs
  Assets/Scripts/Areas/StartArea.cs.meta
  Assets/Scripts/Player/GroundDetector.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Sounds/DoubleAudioSource.cs
  Assets/Scripts/Sounds/Manager/CharacterSounds.cs
  Assets/Scripts/Sounds/Manager/MusicManager.cs
  Assets/Scripts/Sounds/Manager/MusicManager.cs.meta
  Assets/Scripts/Sounds/Manager/PlayList.cs
  Assets/Scripts/Sounds/Manager/PlayList.cs.meta
  Assets/Scripts/Sounds/Util/FadeAudioSource.cs
  ProjectSettings/TagManager.asset
Labels: enhancement

#123 FIX: walking sound
  Assets/Scripts/Sounds/Manager/CharacterSounds.cs
Labels: fix

#128 Sound system/prefab fix
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
Labels: fix

#132 Doc/developer guide
  .github/workflows/documentation.yml
  doc/developer_guide/developer_guide.adoc
  doc/documentation.adoc
Labels: documentation

#131 Sound system/object sounds
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Sounds/DoubleAudioSource.cs
  Assets/Scripts/Sounds/Manager/ObjectManager.cs
  Assets/Scripts/Sounds/Manager/ObjectManager.cs.meta
  Assets/Sounds/Foleys/116679__puniho__rolling-steel-bar.ogg
  Assets/Sounds/Foleys/116679__puniho__rolling-steel-bar.ogg.meta
  Assets/Sounds/Foleys/347777__xmetalcorerx__steel3.wav
  Assets/Sounds/Foleys/347777__xmetalcorerx__steel3.wav.meta
Labels: enhancement

#133 Sound system/fix objects paused in menu
  Assets/Scripts/Player/PlayerController.cs
Labels: fix

#151 ADD: how to doc
  doc/developer_guide/developer_guide.adoc
Labels: documentation

#148 UPDATE: Readme
  README.md
Labels: documentation

#150 Sound system/mixer
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/MenuScripts/AudioSettingsMenu.cs
  Assets/Scripts/MenuScripts/AudioSettingsMenu.cs.meta
  Assets/Scripts/MenuScripts/PauseMenu.cs
  Assets/Scripts/MenuScripts/SettingsMenu.cs
  Assets/Scripts/MenuScripts/SettingsMenu.cs.meta
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Sounds/AudioSettings.cs
  Assets/Scripts/Sounds/AudioSettings.cs.meta
  Assets/Scripts/Sounds/DoubleAudioSource.cs
  Assets/Scripts/Sounds/Manager/CharacterSounds.cs
  Assets/Scripts/Sounds/Manager/MusicManager.cs
  Assets/Scripts/Sounds/Manager/ObjectManager.cs
  Assets/Sounds/Mixer.meta
  Assets/Sounds/Mixer/MainMixer.mixer
  Assets/Sounds/Mixer/MainMixer.mixer.meta
Labels: enhancement

#147 MERGE: Inventory/Improvements to production
  Assets/Prefabs/ContextMenuButton.prefab
  Assets/Prefabs/ContextMenuButton.prefab.meta
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/InventorySlot.prefab
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/ButtonClick.cs
  Assets/Scripts/ButtonClick.cs.meta
  Assets/Scripts/Interaction/Interactable_Pickup.cs
  Assets/Scripts/Inventory/FoodItem.cs
  Assets/Scripts/Inventory/Inventory.cs
  Assets/Scripts/Inventory/InventoryDisplay.cs
  Assets/Scripts/Inventory/InventoryItem.cs
  Assets/Scripts/Inventory/InventoryItem_Consumable.cs
  Assets/Scripts/Inventory/InventoryItem_Consumable.cs.meta
  Assets/Scripts/Inventory/InventoryItem_Equippable.cs
  Assets/Scripts/Inventory/InventoryItem_Equippable.cs.meta
  Assets/Scripts/Inventory/InventoryItem_Usable.cs
  Assets/Scripts/Inventory/InventoryItem_Usable.cs.meta
  Assets/Scripts/Inventory/InventorySlot.cs
  Assets/Scripts/MenuScripts/CloseableMenu.cs
  Assets/Scripts/MenuScripts/InventoryContextMenu.cs
  Assets/Scripts/MenuScripts/InventoryContextMenu.cs.meta
  Assets/Scripts/Player/PlayerProperties.cs
  README.md
  doc/developer_guide/developer_guide.adoc
Labels: improvement, rework

#163 Inventory/production
  Assets/Prefabs/ContextMenuButton.prefab
  Assets/Prefabs/ContextMenuButton.prefab.meta
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/InventorySlot.prefab
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/ButtonClick.cs
  Assets/Scripts/ButtonClick.cs.meta
  Assets/Scripts/Interaction/Interactable_Pickup.cs
  Assets/Scripts/Inventory/FoodItem.cs
  Assets/Scripts/Inventory/Inventory.cs
  Assets/Scripts/Inventory/InventoryDisplay.cs
  Assets/Scripts/Inventory/InventoryItem.cs
  Assets/Scripts/Inventory/InventoryItem_Consumable.cs
  Assets/Scripts/Inventory/InventoryItem_Consumable.cs.meta
  Assets/Scripts/Inventory/InventoryItem_Equippable.cs
  Assets/Scripts/Inventory/InventoryItem_Equippable.cs.meta
  Assets/Scripts/Inventory/InventoryItem_Usable.cs
  Assets/Scripts/Inventory/InventoryItem_Usable.cs.meta
  Assets/Scripts/Inventory/InventorySlot.cs
  Assets/Scripts/MenuScripts/CloseableMenu.cs
  Assets/Scripts/MenuScripts/InventoryContextMenu.cs
  Assets/Scripts/MenuScripts/InventoryContextMenu.cs.meta
  Assets/Scripts/Player/PlayerProperties.cs
Labels: improvement, rework

#167 FIX: #149
  Assets/Prefabs/HUD.prefab
  Assets/Scripts/MenuScripts/CloseableMenu.cs
  Assets/Scripts/MenuScripts/PauseMenu.cs
Labels: fix

#168 UPDATE: Logger to include Warnings and Errors
  Assets/Scripts/Logger.cs
Labels: enhancement

#170 Sound system/sound areas
  Assets/Scripts/Areas/BattleCube.cs
  Assets/Scripts/Areas/FightingArea.cs
  Assets/Scripts/Areas/FightingArea.cs.meta
  Assets/Scripts/Areas/GenericArea.cs
  Assets/Scripts/Areas/GenericArea.cs.meta
  Assets/Scripts/Areas/SoundArea.cs
  Assets/Scripts/Areas/StartArea.cs
  doc/developer_guide/Sound/SoundArea.adoc
  doc/developer_guide/Sound/images/areas_scene_view.png
  doc/developer_guide/Sound/index.adoc
  doc/developer_guide/developer_guide.adoc
Labels: rework

#171 Sound system/ambient sound
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Sounds/DoubleAudioSource.cs
  Assets/Scripts/Sounds/Manager/AmbientSoundManager.cs
  Assets/Scripts/Sounds/Manager/AmbientSoundManager.cs.meta
  Assets/Scripts/Sounds/Manager/MusicManager.cs
  Assets/Sounds/Ambient.meta
  Assets/Sounds/Ambient/123907__alienistcog__machine-noise-bg.aiff
  Assets/Sounds/Ambient/123907__alienistcog__machine-noise-bg.aiff.meta
  doc/developer_guide/Sound/AmbientSound.adoc
  doc/developer_guide/Sound/images/ambient-sound-manager-components.png
  doc/developer_guide/Sound/index.adoc
Labels: enhancement

#180 ADD: Documentation for Inventory Module and Closeable Menu
  Assets/Scripts/Inventory/Inventory.cs
  Assets/Scripts/Inventory/InventoryDisplay.cs
  doc/developer_guide/Inventory/Inventory.adoc
  doc/developer_guide/Inventory/InventoryDisplay.adoc
  doc/developer_guide/Inventory/InventoryItem.adoc
  doc/developer_guide/Inventory/images/InventoryDisplayEditor.png
  doc/developer_guide/Inventory/images/InventoryDisplayLegend.png
  doc/developer_guide/Inventory/images/InventoryEditor.png
  doc/developer_guide/Inventory/index.adoc
  doc/developer_guide/Menu/CloseableMenu.adoc
  doc/developer_guide/Menu/InventoryContextMenu.adoc
  doc/developer_guide/Menu/images/CloseableMenuVariables.png
  doc/developer_guide/developer_guide.adoc
Labels: documentation

#189 FIX: reorder the effects in mixer
  Assets/Sounds/Mixer/MainMixer.mixer
Labels: fix

#185 First StatusEffect and StatAttribute prototype
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Interaction/Interactable_Healthbar.cs
  Assets/Scripts/Interaction/Interactable_PlayerMaxLife.cs
  Assets/Scripts/Interaction/Interactable_Poison.cs
  Assets/Scripts/Interaction/Interactable_Poison.cs.meta
  Assets/Scripts/Player/PlayerHealthbar.cs
  Assets/Scripts/Player/PlayerProperties.cs
  Assets/Scripts/Stat.meta
  Assets/Scripts/Stat/IAttributeHolder.cs
  Assets/Scripts/Stat/IAttributeHolder.cs.meta
  Assets/Scripts/Stat/IStatModifierSource.cs
  Assets/Scripts/Stat/IStatModifierSource.cs.meta
  Assets/Scripts/Stat/StatAttribute.cs
  Assets/Scripts/Stat/StatAttribute.cs.meta
  Assets/Scripts/Stat/StatModifier.cs
  Assets/Scripts/Stat/StatModifier.cs.meta
  Assets/Scripts/Status.meta
  Assets/Scripts/Status/MaxHealthBoostEffect.cs
  Assets/Scripts/Status/MaxHealthBoostEffect.cs.meta
  Assets/Scripts/Status/PoisonEffect.cs
  Assets/Scripts/Status/PoisonEffect.cs.meta
  Assets/Scripts/Status/StatAttributeModifierEffect.cs
  Assets/Scripts/Status/StatAttributeModifierEffect.cs.meta
  Assets/Scripts/Status/StatusEffect.cs
  Assets/Scripts/Status/StatusEffect.cs.meta
  Assets/Scripts/Status/StatusEffectHolder.cs
  Assets/Scripts/Status/StatusEffectHolder.cs.meta
  Assets/Scripts/Status/TimedEffect.cs
  Assets/Scripts/Status/TimedEffect.cs.meta
  Assets/Scripts/Status/TimedStatAttributeModifierEffect.cs
  Assets/Scripts/Status/TimedStatAttributeModifierEffect.cs.meta
Labels: enhancement

#191 FIX: That the Taskboard is not visible in the mirror
  Assets/Materials/Materials/MirrorTexture.mat.meta
  Assets/Materials/Materials/Tasklist.mat
  Assets/Materials/Materials/Tasklist.mat.meta
  Assets/Materials/Taskboard.mat
  Assets/Materials/Taskboard.mat.meta
  Assets/Scenes/TestScene.unity
Labels: fix

#195 ADD: Open pause menu when you tab out of the game
  Assets/Scenes/TestScene.unity
  Assets/Scripts/SceneMaster.cs
  Assets/Scripts/SceneMaster.cs.meta
Labels: enhancement

#199 Sound system/add annoying anvil sound
  Assets/Resources/Sounds/Ambient/321889__duasun__hammer-and-anvil.wav
  Assets/Resources/Sounds/Ambient/321889__duasun__hammer-and-anvil.wav.meta
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Sounds/Manager/AmbientSoundManager.cs
Labels: improvement

#196 REFACTOR: Interactors and Interactable -> they now get the Interactor…
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Interaction/Interactable.cs
  Assets/Scripts/Interaction/InteractableDialogueStarter.cs
  Assets/Scripts/Interaction/InteractableDialogueStarter.cs.meta
  Assets/Scripts/Interaction/InteractableDoNothing.cs
  Assets/Scripts/Interaction/InteractableDoNothing.cs.meta
  Assets/Scripts/Interaction/InteractableHealth.cs
  Assets/Scripts/Interaction/InteractableHealth.cs.meta
  Assets/Scripts/Interaction/InteractableItemPickup.cs
  Assets/Scripts/Interaction/InteractableItemPickup.cs.meta
  Assets/Scripts/Interaction/InteractableMaterialChange.cs
  Assets/Scripts/Interaction/InteractableMaterialChange.cs.meta
  Assets/Scripts/Interaction/InteractableMaxHealth.cs
  Assets/Scripts/Interaction/InteractableMaxHealth.cs.meta
  Assets/Scripts/Interaction/InteractablePushUp.cs
  Assets/Scripts/Interaction/InteractablePushUp.cs.meta
  Assets/Scripts/Interaction/Interactable_Basic.cs
  Assets/Scripts/Interaction/Interactable_ColorChangeCube.cs
  Assets/Scripts/Interaction/Interactable_DialogueHandler.cs
  Assets/Scripts/Interaction/Interactable_Healthbar.cs
  Assets/Scripts/Interaction/Interactable_Pickup.cs
  Assets/Scripts/Interaction/Interactable_PlayerMaxLife.cs
  Assets/Scripts/Interaction/Interactable_PushAway.cs
  Assets/Scripts/Interaction/Interactor.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/StreamingAssetsmmg
  Assets/StreamingAssetsmmg.meta
Labels: improvement

#198 Sound system/playlist creation
  Assets/Playlists.meta
  Assets/Playlists/DefaultBackgroundPlaylist.asset
  Assets/Playlists/DefaultBackgroundPlaylist.asset.meta
  Assets/Playlists/FightingPlaylist.asset
  Assets/Playlists/FightingPlaylist.asset.meta
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Areas/FightingArea.cs
  Assets/Scripts/Areas/FightingArea.cs.meta
  Assets/Scripts/Areas/GenericArea.cs
  Assets/Scripts/Areas/GenericArea.cs.meta
  Assets/Scripts/Areas/SoundArea.cs
  Assets/Scripts/Areas/StartArea.cs
  Assets/Scripts/Areas/StartArea.cs.meta
  Assets/Scripts/Sounds/DoubleAudioSource.cs
  Assets/Scripts/Sounds/Manager/MusicManager.cs
  Assets/Scripts/Sounds/Manager/PlayList.cs
  Assets/Scripts/Sounds/PlaylistScriptable.cs
  Assets/Scripts/Sounds/PlaylistScriptable.cs.meta
  doc/developer_guide/Sound/Playlist.adoc
  doc/developer_guide/Sound/SoundArea.adoc
  doc/developer_guide/Sound/images/playlist-scriptable.png
  doc/developer_guide/Sound/images/sound-area.png
Labels: improvement

#206 ADD: menu component annotation
  Assets/Scripts/Sounds/Manager/AmbientSoundManager.cs
  Assets/Scripts/Sounds/Manager/CharacterSounds.cs
  Assets/Scripts/Sounds/Manager/MusicManager.cs
  Assets/Scripts/Sounds/Manager/ObjectManager.cs
Labels: improvement

#207 ADD: sound system patch notes
  patch_notes.md
Labels: documentation

#222 FIX: Fixes #187 exit button not working
  Assets/Scenes/TestScene.unity
Labels: fix

#220 FIX: mute ambient in menu
  Assets/Scripts/Player/PlayerController.cs
Labels: fix

#213 UPDATE: TestScene with new Taskboard and UwUtoffel for 0.0.0.10 Release
  Assets/Materials/Taskboard.jpg
  Assets/Materials/Taskboard.jpg.meta
  Assets/Materials/Taskboard.mat
  Assets/Materials/Taskboard.png.meta
  Assets/Scenes/TestScene.unity
Labels: improvement

#235 Hotfix/sound area raycast
  Assets/Scenes/TestScene.unity
  doc/developer_guide/Sound/SoundArea.adoc
  doc/developer_guide/Sound/images/ignore-raycast.png
Labels: fix

#238 FIX: first contact collision
  Assets/Scripts/Sounds/Manager/ObjectManager.cs
Labels: fix

#247 ADD: First Setup for the fightingssystem
  Assets/Prefabs/Human.prefab
  Assets/Prefabs/Human.prefab.meta
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Fighting.meta
  Assets/Scripts/Fighting/Attack.cs
  Assets/Scripts/Fighting/Attack.cs.meta
  Assets/Scripts/Fighting/AttackCalculator.cs
  Assets/Scripts/Fighting/AttackCalculator.cs.meta
  Assets/Scripts/Fighting/Hitbox.cs
  Assets/Scripts/Fighting/Hitbox.cs.meta
  Assets/Scripts/Fighting/TestTurret.cs
  Assets/Scripts/Fighting/TestTurret.cs.meta
  Assets/Scripts/NPC.meta
  Assets/Scripts/NPC/NPCProperties.cs
  Assets/Scripts/NPC/NPCProperties.cs.meta
Labels: enhancement

#248 ADD: basic 2D map generator for AI
  Assets/Scenes/AiArena.unity
  Assets/Scenes/AiArena.unity.meta
  Assets/Scenes/TestScene.unity
  Assets/Scripts/AI.meta
  Assets/Scripts/AI/AiWrapper.cs
  Assets/Scripts/AI/AiWrapper.cs.meta
  Assets/Scripts/AI/Cartographer.cs
  Assets/Scripts/AI/Cartographer.cs.meta
  Assets/Scripts/AI/Map.cs
  Assets/Scripts/AI/Map.cs.meta
  Assets/Scripts/AI/MapEntry.cs
  Assets/Scripts/AI/MapEntry.cs.meta
  Assets/Scripts/Scripts.asmdef
  Assets/Scripts/Scripts.asmdef.meta
  Assets/Tests.meta
  Assets/Tests/Ai.meta
  Assets/Tests/Ai/MapTest.cs
  Assets/Tests/Ai/MapTest.cs.meta
  Assets/Tests/Tests.asmdef
  Assets/Tests/Tests.asmdef.meta
  doc/developer_guide/LevelDesign/index.adoc
  doc/developer_guide/developer_guide.adoc
Labels: enhancement

#254 Ai/arena
  Assets/Scenes/AiArena.unity.meta
  Assets/Scripts/AI/AiWrapper.cs
  Assets/Scripts/AI/Cartographer.cs
  Assets/Scripts/AI/MapEntry.cs
  Assets/Tests/Ai/CartographTest.cs
  Assets/Tests/Ai/CartographTest.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#257 Ai/relative map
  Assets/Scenes/AiArena.unity
  Assets/Scripts/AI/Cartographer.cs
  Assets/Scripts/AI/Map.cs
  Assets/Tests/Ai/CartographTest.cs
  Assets/Tests/Ai/MapTest.cs
Labels: enhancement
