Repository ink-inc/MagicMittelalterGame, pull requests merged in 2020-03, with the labels that each got.

#26 ADD: Interactable subtext to HUD
  Assets/Scenes/Main.unity
  Assets/Scripts/Interaction/Interactable.cs
  Assets/Scripts/Interaction/Interactable_ColorChangeCube.cs
  Assets/Scripts/Interaction/Interactor.cs
Labels: enhancement

#27 MERGE: Bugs/lukas
  Assets/Gaia/Data/GS-20200319-171443.asset
  Assets/Gaia/Data/GS-20200319-171443.asset.meta
  Assets/Gaia/Data/GS-20200319-171814.asset
  Assets/Gaia/Data/GS-20200319-171814.asset.meta
  Assets/Gaia/Data/GS-20200319-172129.asset
  Assets/Gaia/Data/GS-20200319-172129.asset.meta
  Assets/Gaia/Data/GS-20200319-172500.asset
  Assets/Gaia/Data/GS-20200319-172500.asset.meta
  Assets/Gaia/Data/GS-20200319-172521.asset
  Assets/Gaia/Data/GS-20200319-172521.asset.meta
  Assets/Gaia/Data/GS-20200319-173135.asset
  Assets/Gaia/Data/GS-20200319-173135.asset.meta
  Assets/Gaia/Data/GS-20200319-173409.asset
  Assets/Gaia/Data/GS-20200319-173409.asset.meta
  Assets/Gaia/Data/GS-20200319-173453.asset
  Assets/Gaia/Data/GS-20200319-173453.asset.meta
  Assets/Gaia/Data/GS-20200319-173513.asset
  Assets/Gaia/Data/GS-20200319-173513.asset.meta
  Assets/Gaia/Data/GS-20200319-182807.asset
  Assets/Gaia/Data/GS-20200319-182807.asset.meta
  Assets/Gaia/Data/GS-20200319-182856.asset
  Assets/Gaia/Data/GS-20200319-182856.asset.meta
  Assets/Gaia/Data/GS-20200319-183109.asset
  Assets/Gaia/Data/GS-20200319-183109.asset.meta
  Assets/Gaia/Data/GS-20200319-183244.asset
  Assets/Gaia/Data/GS-20200319-183244.asset.meta
  Assets/Gaia/Data/GS-20200319-183502.asset
  Assets/Gaia/Data/GS-20200319-183502.asset.meta
  Assets/Gaia/Data/GS-20200319-183607.asset
  Assets/Gaia/Data/GS-20200319-183607.asset.meta
  Assets/Gaia/Data/GS-20200319-183622.asset
  Assets/Gaia/Data/GS-20200319-183622.asset.meta
  Assets/Gaia/Data/GS-20200319-184015.asset
  Assets/Gaia/Data/GS-20200319-184015.asset.meta
  Assets/Gaia/Data/GS-20200319-184041.asset
  Assets/Gaia/Data/GS-20200319-184041.asset.meta
  Assets/Gaia/Data/GS-20200319-184148.asset
  Assets/Gaia/Data/GS-20200319-184148.asset.meta
  Assets/Gaia/Data/GS-20200319-184241.asset
  Assets/Gaia/Data/GS-20200319-184241.asset.meta
  Assets/Gaia/Data/GS-20200319-184424.asset
  Assets/Gaia/Data/GS-20200319-184424.asset.meta
  Assets/Gaia/Data/GS-20200319-184604.asset
  Assets/Gaia/Data/GS-20200319-184604.asset.meta
  Assets/Scripts/MenuScripts/PauseMenu.cs
  Assets/Scripts/Player.meta
  Assets/Scripts/Player/GroundDetector.cs
  Assets/Scripts/Player/GroundDetector.cs.meta
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerController.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: bug

#31 MERGE: Improvements/pause menu improvements
  Assets/Scripts/MenuScripts/PauseMenu.cs
  Assets/Scripts/Player/PlayerController.cs
Labels: enhancement

#33 FIX: #29 and #32 and update texts
  Assets/Scenes/Main.unity
  Assets/Scripts/Interaction/Interactable.cs
  Assets/Scripts/Interaction/Interactor.cs
Labels: enhancement, fix

#34 FIX/ADD: Unify HUD in multiple scenes and add Prefab
  Assets/Gaia/Data/GS-20200323-143930.asset
  Assets/Gaia/Data/GS-20200323-143930.asset.meta
  Assets/Gaia/Data/GS-20200323-151404.asset
  Assets/Gaia/Data/GS-20200323-151404.asset.meta
  Assets/Prefabs.meta
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/HUD.prefab.meta
  Assets/SceneObjects/Parent.prefab
  Assets/Scenes/Main.unity
  Assets/Scenes/Terrain.unity
  Assets/Scripts/Interaction/Interactor.cs
Labels: fix

#45 REMOVE: Unnecessary comments in interactor
  Assets/Scripts/Interaction/Interactor.cs
Labels: fix

#47 UPDATE Unity to Version 2019.3.6f1
  Assets/Gaia/Scripts/Editor/ExportTerrain.cs
  Assets/Gaia/Scripts/ResourcesSystem/GaiaWorldManager.cs
  Assets/Gaia/Scripts/StampingSystem/Stamper.cs
  Assets/Gaia/Scripts/Utils/TerrainHelper.cs
  Assets/Gaia/Scripts/Utils/UnityHeightMap.cs
  Packages/manifest.json
  ProjectSettings/EditorSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: improvement

#52 FIX: #39 and #50
  Assets/Scripts/Interaction/Interactor.cs
  Assets/Scripts/Logger.cs
Labels: fix

#54 ADD: Debug Screen
  Assets/DebugScreen.cs
  Assets/DebugScreen.cs.meta
  Assets/Gaia/Data/GS-20200324-145704.asset
  Assets/Gaia/Data/GS-20200324-145704.asset.meta
  Assets/Prefabs/HUD.prefab
Labels: enhancement

#55 ADD: Player Healthbar
  Assets/Gaia/Data/GS-20200324-180839.asset
  Assets/Gaia/Data/GS-20200324-180839.asset.meta
  Assets/Gaia/Data/GS-20200324-181330.asset
  Assets/Gaia/Data/GS-20200324-181330.asset.meta
  Assets/Gaia/Scripts/Editor/PWCommonMenuAG.cs.meta
  Assets/Materials/Interactable_4.mat
  Assets/Materials/Interactable_4.mat.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/Interaction/Interactable_Healthbar.cs
  Assets/Scripts/Interaction/Interactable_Healthbar.cs.meta
  Assets/Scripts/Interaction/Interactable_PlayerMaxLife.cs
  Assets/Scripts/Interaction/Interactable_PlayerMaxLife.cs.meta
  Assets/Scripts/Player/PlayerHealthbar.cs
  Assets/Scripts/Player/PlayerHealthbar.cs.meta
  Assets/Scripts/Player/PlayerProperties.cs
  Assets/Scripts/Player/PlayerProperties.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: minor feature

#62 MERGE: Improvements/lukas 26 03 2020
  .gitignore
  Assets/Models/UwUtoffel.Materials.meta
  Assets/Models/UwUtoffel.Materials/Material.001.asset
  Assets/Models/UwUtoffel.Materials/Material.001.asset.meta
  Assets/Models/UwUtoffel.Meshes.meta
  Assets/Models/UwUtoffel.Meshes/Sphere.asset
  Assets/Models/UwUtoffel.Meshes/Sphere.asset.meta
  Assets/Models/UwUtoffel.Textures.meta
  Assets/Models/UwUtoffel.Textures/kawai.png
  Assets/Models/UwUtoffel.Textures/kawai.png.meta
  Assets/Models/UwUtoffel.prefab
  Assets/Models/UwUtoffel.prefab.meta
  Assets/Models/kartoffel_final.Materials.meta
  Assets/Models/kartoffel_final.Materials/Material.003.asset
  Assets/Models/kartoffel_final.Materials/Material.003.asset.meta
  Assets/Models/kartoffel_final.Meshes.meta
  Assets/Models/kartoffel_final.Meshes/Sphere.002.asset
  Assets/Models/kartoffel_final.Meshes/Sphere.002.asset.meta
  Assets/Models/kartoffel_final.Textures.meta
  Assets/Models/kartoffel_final.Textures/Untitled.png
  Assets/Models/kartoffel_final.Textures/Untitled.png.meta
  Assets/Models/kartoffel_final.prefab
  Assets/Models/kartoffel_final.prefab.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerProperties.cs
  Assets/UniGLTF.meta
Labels: enhancement, improvement

#61 MERGE: Talkingsystem/development lukas
  Assets/Scenes/Main.unity
  Assets/Scripts/Dialogue.meta
  Assets/Scripts/Dialogue/DialogueHandler.cs
  Assets/Scripts/Dialogue/DialogueHandler.cs.meta
  Assets/Scripts/Dialogue/DialogueObject.cs
  Assets/Scripts/Dialogue/DialogueObject.cs.meta
  Assets/Scripts/Dialogue/DialogueRepository.cs
  Assets/Scripts/Dialogue/DialogueRepository.cs.meta
  Assets/Scripts/Dialogue/DialogueService.cs
  Assets/Scripts/Dialogue/DialogueService.cs.meta
  Assets/Scripts/Interaction/Interactable_DialogueHandler.cs
  Assets/Scripts/Interaction/Interactable_DialogueHandler.cs.meta
  Assets/Scripts/Player/PlayerController.cs
  TestDialog.txt
  TestDialog.txt.meta
Labels: enhancement

#69 UPDATE: HealthBar added in HUD Prefab and script improvements
  Assets/Prefabs/HUD.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Player/PlayerHealthbar.cs
  Assets/UniGLTF.meta
Labels: enhancement

#70 ADD: Compass
  Assets/Materials/Textures.meta
  Assets/Materials/Textures/Chess.png
  Assets/Materials/Textures/Chess.png.meta
  Assets/Materials/Textures/compass.png
  Assets/Materials/Textures/compass.png.meta
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/Logger.prefab
  Assets/Prefabs/Logger.prefab.meta
  Assets/Scripts/HUD.meta
  Assets/Scripts/HUD/Compass.cs
  Assets/Scripts/HUD/Compass.cs.meta
  Assets/Scripts/HUD/DebugScreen.cs
  Assets/Scripts/HUD/DebugScreen.cs.meta
Labels: enhancement

#73 ADD : Menu Button
  Assets/Gaia/Data/GS-20200327-164357.asset
  Assets/Gaia/Data/GS-20200327-164357.asset.meta
  Assets/Gaia/Data/GS-20200327-164820.asset
  Assets/Gaia/Data/GS-20200327-164820.asset.meta
  Assets/Prefabs/HUD.prefab
  Assets/Scenes/Main.unity
  Assets/Scenes/StartMenu.unity
  Assets/Scripts/HUD/Compass.cs
  Assets/Scripts/MenuScripts/MainMenu.cs
  Assets/Scripts/MenuScripts/PauseMenu.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, minor feature

#77 ADD: Main Menu Scene Selector
  Assets/Gaia/Data/GS-20200328-123542.asset
  Assets/Gaia/Data/GS-20200328-123542.asset.meta
  Assets/Gaia/Data/GS-20200328-123735.asset
  Assets/Gaia/Data/GS-20200328-123735.asset.meta
  Assets/Gaia/Data/GS-20200328-123753.asset
  Assets/Gaia/Data/GS-20200328-123753.asset.meta
  Assets/Gaia/Data/GS-20200328-123802.asset
  Assets/Gaia/Data/GS-20200328-123802.asset.meta
  Assets/Gaia/Data/GS-20200328-123936.asset
  Assets/Gaia/Data/GS-20200328-123936.asset.meta
  Assets/Prefabs/UI.meta
  Assets/Prefabs/UI/SceneSelectorSceneObject.prefab
  Assets/Prefabs/UI/SceneSelectorSceneObject.prefab.meta
  Assets/Scenes/StartMenu.unity
  Assets/Scripts/MenuScripts/MainMenu.cs
  Assets/Scripts/MenuScripts/PauseMenu.cs
  Assets/inktopus.png
  Assets/inktopus.png.meta
Labels: enhancement

#79 RENAME: Main to Test Scene
  Assets/Scenes/StartMenu.unity
  Assets/Scenes/TestMenu.unity
  Assets/Scenes/TestMenu.unity.meta
  Assets/Scenes/TestScene.unity
  Assets/Scenes/TestScene.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: minor feature

#85 Doc/cloning
  .gitignore
  README.md
Labels: documentation

#101 ADD: description for lfs handling
  README.md
Labels: documentation
