Repository ink-inc/MagicMittelalterGame, pull requests merged in 2020-05, with the labels that each got.

#264 Ai/academy
  Assets/Scripts/AI/BaseAgent.cs
  Assets/Scripts/AI/MmgAcademy.cs
  Assets/Scripts/AI/MmgAcademy.cs.meta
Labels: enhancement

#205 Doc/ai requirements
  doc/AI-requirements.adoc
  doc/developer_guide/Ai/FeatureEngineering.adoc
  doc/documentation.adoc
Labels: documentation

#210 ADD: Interactable to take an item and drag it around
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Interaction/InteractableDragWithYou.cs
  Assets/Scripts/Interaction/InteractableDragWithYou.cs.meta
  ProjectSettings/TagManager.asset
Labels: enhancement

#267 FIX: Various fixes, quality settings change, and custom splash screen
  Assets/Scripts/HUD/DebugScreen.cs
  Assets/Scripts/Quest/QuestMarkerManager.cs
  Assets/Scripts/Sounds/Manager/MusicManager.cs
  Assets/Themes/DefaultTheme.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: improvement

#268 ADD: side channel for configuartion
  Assets/Prefabs/Agent.prefab
  Assets/Scenes/AiArena.unity
  Assets/Scripts/AI/BaseAgent.cs
  Assets/Scripts/AI/Cartographer.cs
  Assets/Scripts/AI/ConfigurationSideChannel.cs
  Assets/Scripts/AI/ConfigurationSideChannel.cs.meta
  Assets/Scripts/AI/MmgAcademy.cs
Labels: enhancement

#252 ADD: Combos to the fightingssystem (pls look at it)
  Assets/Prefabs/Human.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Fighting/Attack.cs
  Assets/Scripts/Fighting/AttackCalculator.cs
  Assets/Scripts/Fighting/AttackCombo.cs
  Assets/Scripts/Fighting/AttackCombo.cs.meta
  Assets/Scripts/Fighting/AttackCombos.meta
  Assets/Scripts/Fighting/AttackCombos/FromHeadToToe.asset
  Assets/Scripts/Fighting/AttackCombos/FromHeadToToe.asset.meta
  Assets/Scripts/Fighting/AttackCombos/HeadCrusher.asset
  Assets/Scripts/Fighting/AttackCombos/HeadCrusher.asset.meta
  Assets/Scripts/Fighting/AttackCombos/NoMoreArms.asset
  Assets/Scripts/Fighting/AttackCombos/NoMoreArms.asset.meta
  Assets/Scripts/Fighting/Attacker.cs
  Assets/Scripts/Fighting/Attacker.cs.meta
  Assets/Scripts/Fighting/Hitbox.cs
  Assets/Scripts/Fighting/TestTurret.cs
  Assets/Scripts/Utility.cs
Labels: enhancement

#269 MERGE: master partially with reversion of namespaces
  Assets/Gaia/Scripts/Common/Editor/PWEditor.cs
  Assets/Gaia/Scripts/Editor/GaiaDefaultsEditor.cs
  Assets/Gaia/Scripts/Editor/GaiaDefinesEditor.cs
  Assets/Gaia/Scripts/Editor/GaiaResourceEditor.cs
  Assets/Gaia/Scripts/Editor/GaiaSessionEditor.cs
  Assets/Gaia/Scripts/Editor/GaiaSessionManagerEditor.cs
  Assets/Gaia/Scripts/Editor/GaiaStdMenu.cs
  Assets/Gaia/Scripts/Editor/PWCommonMenuAG.cs
  Assets/Gaia/Scripts/Editor/ResourceVisualiserEditor.cs
  Assets/Gaia/Scripts/Editor/ScannerEditor.cs
  Assets/Gaia/Scripts/Editor/SpawnerEditor.cs
  Assets/Gaia/Scripts/Editor/SpawnerGroupEditor.cs
  Assets/Gaia/Scripts/Editor/StamperEditor.cs
  Assets/Gaia/Scripts/Editor/TerrainHelperEditor.cs
  Assets/Scripts/Editor/LoggerEditor.cs
  Assets/Scripts/HUD/Compass.cs
  Assets/Scripts/HUD/DebugScreen.cs
  Assets/Scripts/Interaction/InteractableHealth.cs
  Assets/Scripts/Interaction/InteractableItemPickup.cs
  Assets/Scripts/Interaction/InteractableMaxHealth.cs
  Assets/Scripts/Interaction/Interactable_ProceedQuest.cs
  Assets/Scripts/Interaction/Interactable_StartQuest.cs
  Assets/Scripts/Inventory/Inventory.cs
  Assets/Scripts/Inventory/InventoryDisplay.cs
  Assets/Scripts/Inventory/InventoryItem.cs
  Assets/Scripts/Inventory/InventoryItem_Consumable.cs
  Assets/Scripts/Inventory/InventoryItem_Equippable.cs
  Assets/Scripts/Inventory/InventoryItem_Usable.cs
  Assets/Scripts/Inventory/InventorySlot.cs
  Assets/Scripts/MenuScripts/CloseableMenu.cs
  Assets/Scripts/MenuScripts/ControlsMenu.cs
  Assets/Scripts/MenuScripts/InventoryContextMenu.cs
  Assets/Scripts/MenuScripts/PauseMenu.cs
  Assets/Scripts/MenuScripts/StartMenu.cs
  Assets/Scripts/Player/GroundDetector.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerHealthbar.cs
  Assets/Scripts/Player/PlayerProperties.cs
  Assets/Scripts/Quest/Quest.cs
  Assets/Scripts/Quest/QuestHandler.cs
  Assets/Scripts/Quest/QuestMarker.cs
  Assets/Scripts/Quest/QuestMarkerManager.cs
  Assets/Scripts/Quest/QuestRepository.cs
  Assets/Scripts/Quest/QuestSlot.cs
  Assets/Scripts/Quest/QuestStage.cs
  Assets/Scripts/Quest/QuestjournalDisplay.cs
  Assets/Scripts/Quest/Questlog.cs
  Assets/Scripts/Quest/StageSlot.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: fix

#274 Ai/properties
  Assets/Data/Attribute/Player/PlayerHealth.asset
  Assets/Prefabs/Agent.prefab
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scripts/AI/AiWrapper.cs
  Assets/Scripts/Character.meta
  Assets/Scripts/Character/CharacterProperties.cs
  Assets/Scripts/Character/CharacterProperties.cs.meta
  Assets/Scripts/Character/NPC.meta
  Assets/Scripts/Character/NPC/NpcProperties.cs
  Assets/Scripts/Character/Player.meta
  Assets/Scripts/Character/Player/GroundDetector.cs
  Assets/Scripts/Character/Player/GroundDetector.cs.meta
  Assets/Scripts/Character/Player/PlayerController.cs
  Assets/Scripts/Character/Player/PlayerController.cs.meta
  Assets/Scripts/Character/Player/PlayerHealthbar.cs
  Assets/Scripts/Character/Player/PlayerHealthbar.cs.meta
  Assets/Scripts/Character/Player/PlayerProperties.cs
  Assets/Scripts/Character/Player/PlayerProperties.cs.meta
  Assets/Scripts/HUD/DebugScreen.cs
  Assets/Scripts/Interaction/InteractableHealth.cs
  Assets/Scripts/Inventory/Inventory.cs
  Assets/Scripts/Inventory/InventoryDisplay.cs
  Assets/Scripts/Player/GroundDetector.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerHealthbar.cs
  Assets/Scripts/Player/PlayerProperties.cs
  Assets/Scripts/Stat/AttributeType.cs
  Assets/Scripts/Stat/StatAttribute.cs
  Assets/Scripts/Status/PoisonEffect.cs
  Assets/Scripts/Util/Float.cs
  Assets/Scripts/Util/FloatCalculation.cs
  Assets/Scripts/Util/FloatVariable.cs
  Assets/Scripts/Util/RangedFloatVariableClamp.cs
  Assets/Scripts/Util/RangedFloatVariableClamp.cs.meta
Labels: enhancement

#272 Ai/map scale
  Assets/Scripts/AI/BaseAgent.cs
  Assets/Scripts/AI/Cartographer.cs
  Assets/Scripts/AI/Map.cs
Labels: enhancement

#276 Ai/more properties
  Assets/Scripts/AI/AiWrapper.cs
  Assets/Scripts/AI/ConfigurationSideChannel.cs
  Assets/Scripts/Character/CharacterProperties.cs
  doc/developer_guide/Ai/Observation.adoc
  doc/developer_guide/Ai/index.adoc
  doc/developer_guide/developer_guide.adoc
Labels: enhancement

#279 Ai/second agent
  Assets/Materials/TeamBlue.mat
  Assets/Materials/TeamBlue.mat.meta
  Assets/Materials/TeamRed.mat
  Assets/Materials/TeamRed.mat.meta
  Assets/Scenes/AiArena.unity
  Assets/Scripts/AI/BaseAgent.cs
  Assets/Scripts/AI/MmgAcademy.cs
  Assets/Scripts/Character/CharacterProperties.cs
  Assets/Scripts/Character/NPC/NpcProperties.cs
Labels: enhancement

#273 Improvements/npc properties
  Assets/Data/Attribute/Player/PlayerHealth.asset
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scripts/Character.meta
  Assets/Scripts/Character/CharacterProperties.cs
  Assets/Scripts/Character/CharacterProperties.cs.meta
  Assets/Scripts/Character/NPC.meta
  Assets/Scripts/Character/NPC/NPCProperties.cs.meta
  Assets/Scripts/Character/NPC/NpcProperties.cs
  Assets/Scripts/Character/NPC/NpcProperties.cs.meta
  Assets/Scripts/Character/Player.meta
  Assets/Scripts/Character/Player/GroundDetector.cs
  Assets/Scripts/Character/Player/GroundDetector.cs.meta
  Assets/Scripts/Character/Player/PlayerController.cs
  Assets/Scripts/Character/Player/PlayerController.cs.meta
  Assets/Scripts/Character/Player/PlayerHealthbar.cs
  Assets/Scripts/Character/Player/PlayerHealthbar.cs.meta
  Assets/Scripts/Character/Player/PlayerProperties.cs
  Assets/Scripts/Character/Player/PlayerProperties.cs.meta
  Assets/Scripts/HUD/DebugScreen.cs
  Assets/Scripts/Interaction/InteractableHealth.cs
  Assets/Scripts/Inventory/Inventory.cs
  Assets/Scripts/Inventory/InventoryDisplay.cs
  Assets/Scripts/Player/GroundDetector.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerHealthbar.cs
  Assets/Scripts/Player/PlayerProperties.cs
  Assets/Scripts/Stat/AttributeType.cs
  Assets/Scripts/Stat/StatAttribute.cs
  Assets/Scripts/Status/PoisonEffect.cs
  Assets/Scripts/Util/Float.cs
  Assets/Scripts/Util/FloatCalculation.cs
  Assets/Scripts/Util/FloatVariable.cs
  Assets/Scripts/Util/RangedFloatVariableClamp.cs
  Assets/Scripts/Util/RangedFloatVariableClamp.cs.meta
Labels: improvement

#281 AI: validation overhaul
  Assets/Data/Attribute/Player/Default/DefaultTeamId.asset
  Assets/Data/Attribute/Player/Default/DefaultTeamId.asset.meta
  Assets/Data/Attribute/Player/Team1.asset
  Assets/Data/Attribute/Player/Team1.asset.meta
  Assets/Data/Attribute/Player/Team2.asset
  Assets/Data/Attribute/Player/Team2.asset.meta
  Assets/Prefabs/Agent.prefab
  Assets/Prefabs/Arena.prefab
  Assets/Prefabs/Arena.prefab.meta
  Assets/Scenes/AiArena.unity
  Assets/Scripts/AI/AiWrapper.cs
  Assets/Scripts/AI/Arena.cs
  Assets/Scripts/AI/Arena.cs.meta
  Assets/Scripts/AI/BaseAgent.cs
  Assets/Scripts/AI/ConfigurationSideChannel.cs
  Assets/Scripts/AI/Map.cs
  Assets/Scripts/AI/MmgAcademy.cs
  Assets/Scripts/Character/NPC/NpcProperties.cs
Labels: rework

#283 Ai/orient obs
  Assets/Prefabs/Agent.prefab
  Assets/Prefabs/Arena.prefab
  Assets/Scenes/AiArena.unity
  Assets/Scripts/AI/AiWrapper.cs
  Assets/Scripts/AI/ConfigurationSideChannel.cs
  Assets/Scripts/AI/MmgAcademy.cs
Labels: enhancement

#284 Ai/set scale only once
  Assets/Scripts/AI/BaseAgent.cs
  Assets/Scripts/AI/MmgAcademy.cs
Labels: minor rework

#289 FIX: editor references
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
Labels: fix

#290 Refactor controller logic from player controller to universal character controller
  Assets/Prefabs/PlayerBelongings.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Character/CharacterController.cs
  Assets/Scripts/Character/CharacterController.cs.meta
  Assets/Scripts/Character/CharacterProperties.cs
  Assets/Scripts/Character/JumpStatus.cs
  Assets/Scripts/Character/JumpStatus.cs.meta
  Assets/Scripts/Character/NPC/NPCProperties.cs.meta
  Assets/Scripts/Character/NPC/NpcProperties.cs.meta
  Assets/Scripts/Character/Player/PlayerController.cs
  Assets/Scripts/Quest/QuestjournalDisplay.cs
Labels: rework

#292 Npc/rework jump
  Assets/Scripts/Character/CharacterController.cs
Labels: minor rework
