Repository ink-inc/MagicMittelalterGame, pull requests merged in 2021-01, with the labels that each got.

#266 ADD: Basic Doc for Theme Manager
  doc/developer_guide/Themes/Theme.adoc
  doc/developer_guide/Themes/ThemeManager.adoc
  doc/developer_guide/Themes/ThemeTarget.adoc
  doc/developer_guide/Themes/images/ImageTarget.png
  doc/developer_guide/Themes/images/Theme.png
  doc/developer_guide/Themes/images/ThemeManager.png
  doc/developer_guide/Themes/index.adoc
  doc/developer_guide/developer_guide.adoc
Labels: documentation

#294 Ai/visibility
  Assets/Scripts/AI/Agents/BaseAgent.cs
  Assets/Scripts/AI/Cartographer.cs
Labels: enhancement

#296 ADD: meta-data
  ProjectSettings/ProjectSettings.asset
Labels: improvement

#300 UPDATE: barracuda in order to allow import onnx files generated from BA
  Packages/manifest.json
Labels: improvement

#302 UPDATE: bump unity editor to 2020.2
  Assets/Scripts/Character/NPC/NPCProperties.cs.meta
  Assets/Scripts/Character/NPC/NpcProperties.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: Linux
